In [1]:
import torch
import numpy as np

In [2]:
t = torch.tensor([1,2,3])

In [3]:
t[1]

tensor(2)

In [4]:
t.dtype

torch.int64

In [5]:
t = torch.FloatTensor([1,2,3])
t.dtype

torch.float32

In [6]:
t = torch.LongTensor([1,2,3])
t.dtype

torch.int64

In [8]:
np_array = np.arange(12).reshape(3,4)
np_array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [9]:
torch.from_numpy(np_array)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]], dtype=torch.int32)

In [10]:
np_array.dtype

dtype('int32')

In [12]:
t = torch.tensor([12,2,3],dtype = torch.float32)
t.dtype

torch.float32

In [13]:
t = torch.tensor([12,2,3],dtype = torch.int)
t.dtype

torch.int32

In [14]:
t = torch.tensor([12,2,3],dtype = torch.long)
t.dtype

torch.int64

In [2]:
torch.rand(2,3)

tensor([[0.6269, 0.1236, 0.6392],
        [0.8320, 0.3594, 0.9357]])

In [6]:
t = torch.randn(2,3)

In [7]:
t.shape

torch.Size([2, 3])

In [8]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [9]:
torch.ones(2,2)

tensor([[1., 1.],
        [1., 1.]])

In [11]:
x = torch.zeros_like(t)
x

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [12]:
x = torch.randn_like(t)
x

tensor([[-0.8730, -2.5106,  1.1509],
        [ 1.0038,  1.3538, -0.2965]])

In [13]:
t.size(0)

2

In [14]:
t.shape[1]

3

In [15]:
t.device

device(type='cpu')

In [17]:
torch.cuda.is_available()

True

In [18]:
t = t.to("cuda")

In [19]:
t.device

device(type='cuda', index=0)

In [23]:
t = t.to("cpu")

In [24]:
t.type(torch.float32)

tensor([[ 0.4014, -1.3736,  1.2733],
        [-0.9840,  0.9009, -0.0555]])

In [25]:
t.dtype

torch.float32

In [26]:
t.long()

tensor([[ 0, -1,  1],
        [ 0,  0,  0]])

In [27]:
t.float()

tensor([[ 0.4014, -1.3736,  1.2733],
        [-0.9840,  0.9009, -0.0555]])

torch.float32

In [28]:
t

tensor([[ 0.4014, -1.3736,  1.2733],
        [-0.9840,  0.9009, -0.0555]])

In [29]:
t + 3

tensor([[3.4014, 1.6264, 4.2733],
        [2.0160, 3.9009, 2.9445]])

In [30]:
t1 = torch.ones(2,3)

In [31]:
t1

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [32]:
t + t1

tensor([[ 1.4014, -0.3736,  2.2733],
        [ 0.0160,  1.9009,  0.9445]])

In [33]:
t.add(t1)

tensor([[ 1.4014, -0.3736,  2.2733],
        [ 0.0160,  1.9009,  0.9445]])

In [34]:
t

tensor([[ 0.4014, -1.3736,  1.2733],
        [-0.9840,  0.9009, -0.0555]])

In [35]:
t.add_(t1)

tensor([[ 1.4014, -0.3736,  2.2733],
        [ 0.0160,  1.9009,  0.9445]])

In [36]:
t

tensor([[ 1.4014, -0.3736,  2.2733],
        [ 0.0160,  1.9009,  0.9445]])

In [37]:
t.matmul(t.T)

tensor([[7.2712, 1.4594],
        [1.4594, 4.5057]])

In [38]:
t

tensor([[ 1.4014, -0.3736,  2.2733],
        [ 0.0160,  1.9009,  0.9445]])

In [39]:
t@t.T

tensor([[7.2712, 1.4594],
        [1.4594, 4.5057]])

In [40]:
t.sum().

tensor(6.1625)

In [41]:
t.sum().item()

6.162511825561523

In [43]:
t.numpy()

array([[ 1.4014049 , -0.3735509 ,  2.273261  ],
       [ 0.01603001,  1.900896  ,  0.94447094]], dtype=float32)

In [44]:
t = torch.randn(4,6)

In [45]:
t.shape

torch.Size([4, 6])

In [46]:
t

tensor([[ 1.4430, -0.4749, -1.7306,  1.8659,  0.0972,  0.2431],
        [-1.3665, -0.4376, -0.6252,  0.6800, -0.5202, -0.2374],
        [-0.1241,  1.0643, -0.1692,  2.0879, -2.9595,  2.0007],
        [ 0.5307,  1.3573,  1.8104, -0.1413,  0.1886,  0.0471]])

In [47]:
t.view(3,8)

tensor([[ 1.4430, -0.4749, -1.7306,  1.8659,  0.0972,  0.2431, -1.3665, -0.4376],
        [-0.6252,  0.6800, -0.5202, -0.2374, -0.1241,  1.0643, -0.1692,  2.0879],
        [-2.9595,  2.0007,  0.5307,  1.3573,  1.8104, -0.1413,  0.1886,  0.0471]])

In [48]:
t.reshape(2,12)

tensor([[ 1.4430, -0.4749, -1.7306,  1.8659,  0.0972,  0.2431, -1.3665, -0.4376,
         -0.6252,  0.6800, -0.5202, -0.2374],
        [-0.1241,  1.0643, -0.1692,  2.0879, -2.9595,  2.0007,  0.5307,  1.3573,
          1.8104, -0.1413,  0.1886,  0.0471]])

In [49]:
t

tensor([[ 1.4430, -0.4749, -1.7306,  1.8659,  0.0972,  0.2431],
        [-1.3665, -0.4376, -0.6252,  0.6800, -0.5202, -0.2374],
        [-0.1241,  1.0643, -0.1692,  2.0879, -2.9595,  2.0007],
        [ 0.5307,  1.3573,  1.8104, -0.1413,  0.1886,  0.0471]])

In [50]:
t.squeeze()

tensor([[ 1.4430, -0.4749, -1.7306,  1.8659,  0.0972,  0.2431],
        [-1.3665, -0.4376, -0.6252,  0.6800, -0.5202, -0.2374],
        [-0.1241,  1.0643, -0.1692,  2.0879, -2.9595,  2.0007],
        [ 0.5307,  1.3573,  1.8104, -0.1413,  0.1886,  0.0471]])

In [52]:
t.requires_grad

False

In [54]:
t = torch.ones(2,2,requires_grad=True)

In [55]:
t.requires_grad

True

In [56]:
y = t + 5

In [57]:
y

tensor([[6., 6.],
        [6., 6.]], grad_fn=<AddBackward0>)

In [69]:
z = y*2

In [70]:
z

tensor([[12., 12.],
        [12., 12.]], grad_fn=<MulBackward0>)

In [71]:
out = z.mean()

In [72]:
out

tensor(12., grad_fn=<MeanBackward0>)

In [73]:
out.backward()

In [78]:
t.grad

tensor([[1., 1.],
        [1., 1.]])

In [80]:
out.grad

D:\software\miniconda\lib\site-packages\torch\_tensor.py:1083: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at  C:\cb\pytorch_1000000000000\work\build\aten\src\ATen/core/TensorBody.h:482.)
  return self._grad
